name: mission-data-recorder

on:
  push:
    branches: main
  workflow_dispatch:

jobs:
  tii-mission-data-recorder-deb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y --no-install-recommends \
            build-essential \
            debhelper \
            dh-make \
            fakeroot

      - name: Build Debian package
        run: |
          ./packaging/package.sh \
            -m "$(realpath .)" \
            -v 1.0.0 \
            -c "$(git rev-parse HEAD)" \
            -g "$(git log --date=format:%Y%m%d --pretty=~git%cd.%h -n 1)" \
            -b "$GITHUB_RUN_NUMBER"

      - name: Install jfrog CLI tool
        uses: jfrog/setup-jfrog-cli@v1
        with:
          version: 1.45.2
        env:
          JF_ARTIFACTORY_1: ${{ secrets.ARTIFACTORY_TOKEN }}

      - name: Upload to Artifactory
        env:
          ARTIFACTORY_REPO: debian-public-local
          DISTRIBUTION: focal
          COMPONENT: fog-sw
          ARCHITECTURE: amd64
        run: |
          set -exu
          jfrog rt ping
          pkg=$(find "$GITHUB_WORKSPACE" -name 'mission-data-recorder*.deb')
          jfrog rt u --deb "$DISTRIBUTION/$COMPONENT/$ARCHITECTURE" \
                     --target-props COMMIT="$GITHUB_SHA" \
                     "$pkg" \
                     "$ARTIFACTORY_REPO"
          jfrog rt build-publish
          jfrog rt bpr "$ARTIFACTORY_REPO" \
                       --status dev \
                       --comment "development build"
