name: mission-data-recorder

on:
  push:
    branches: main
  workflow_dispatch:

jobs:
  tii-mission-data-recorder:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.PACKAGES_USER }}
          password: ${{ secrets.PACKAGES_TOKEN }}

      - name: Build tii-mission-data-recorder image and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/tiiuae/tii-mission-data-recorder:latest
