name: mission-data-recorder

on:
  push:
    branches: main
  pull_request:
    branches: main
  workflow_dispatch:

jobs:
  tii-mission-data-recorder-deb:
    runs-on: ubuntu-latest
    container: ros:foxy-ros-core
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y --no-install-recommends \
            build-essential \
            debhelper \
            dh-make \
            fakeroot \
            g++ \
            gcc \
            git \
            ros-foxy-ros2bag \
            ros-foxy-rosbag2 \
            ros-foxy-rosbag2-compression \
            ros-foxy-rosbag2-converter-default-plugins \
            ros-foxy-rosbag2-cpp \
            ros-foxy-rosbag2-storage \
            ros-foxy-rosbag2-storage-default-plugins \
            ros-foxy-rosbag2-transport

      - name: Build Debian package
        run: |
          set -exu
          ./packaging/common/package.sh \
            -m "$(realpath .)" \
            -v 1.0.0 \
            -c "$(git rev-parse HEAD)" \
            -g "$(git log --date=format:%Y%m%d --pretty=~git%cd.%h -n 1)" \
            -b "$GITHUB_RUN_NUMBER"

      - name: Install jfrog CLI tool
        env:
          JFROG_CLI_URL: https://artifactory.ssrc.fi/artifactory/gen-public-local/tools/jfrog/jfrog-1.45.2.tar.gz
        if: github.event_name == 'push'
        run: |
          set -exu
          mkdir -p "$GITHUB_WORKSPACE/.jfrog/bin"
          curl -L "$JFROG_CLI_URL" -o "$GITHUB_WORKSPACE/.jfrog/jfrog.tar.gz"
          tar -C "$GITHUB_WORKSPACE/.jfrog/bin" -zxf "$GITHUB_WORKSPACE/.jfrog/jfrog.tar.gz"
          echo "$GITHUB_WORKSPACE/.jfrog/bin" >> "$GITHUB_PATH"
          echo "JFROG_CLI_HOME_DIR=$GITHUB_WORKSPACE/.jfrog" >> "$GITHUB_ENV"

      - name: Upload to Artifactory
        env:
          ARTIFACTORY_TOKEN: ${{ secrets.ARTIFACTORY_TOKEN }}
          ARTIFACTORY_REPO: debian-public-local
          DISTRIBUTION: focal
          COMPONENT: fog-sw
          ARCHITECTURE: amd64
          BUILD_NAME: mission-data-recorder
          CI: true
        if: github.event_name == 'push'
        run: |
          set -exu
          jfrog rt c import "$ARTIFACTORY_TOKEN"
          jfrog rt ping
          pkg=$(find "$GITHUB_WORKSPACE" -name 'mission-data-recorder*.deb')
          jfrog rt u --deb "$DISTRIBUTION/$COMPONENT/$ARCHITECTURE" \
                     --target-props COMMIT="$GITHUB_SHA" \
                     --build-name "$BUILD_NAME" \
                     --build-number "$GITHUB_SHA" \
                     "$pkg" \
                     "$ARTIFACTORY_REPO"
          jfrog rt build-publish "$BUILD_NAME" "$GITHUB_SHA"
          jfrog rt bpr "$BUILD_NAME" "$GITHUB_SHA" "$ARTIFACTORY_REPO" \
                       --status dev \
                       --comment "development build"
