name: mission-data-recorder

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
    branches:
      - main
    tags:
      - "v*"
  repository_dispatch:
    types: [fog-ros-baseimage-update]
  workflow_dispatch:

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: docker/setup-buildx-action@v1

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/tiiuae/tii-mission-data-recorder
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=sha,format=short
            type=raw,value=latest

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  run-linter:
    runs-on: ubuntu-latest
    container: ghcr.io/tiiuae/fog-ros-baseimage:builder-latest
    steps:
      - uses: actions/checkout@v2

      - name: Prepare environment
        shell: bash
        run: ./lint.sh

      - uses: golangci/golangci-lint-action@v2
        with:
          args: ${{ env.lint_dirs }}
